import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "fr" | "en" | "nl" | "de";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "fr",
  setLang: () => {},
  t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navbar
    "nav.login": "Connexion",
    "nav.getStarted": "Commencer",
    "nav.dashboard": "Tableau de bord",
    "nav.demoDashboard": "Demo Dashboard",
    "nav.logout": "Déconnexion",
    // Hero
    "hero.badge": "🇧🇪 🇫🇷 Conçu pour les freelances belges & français",
    "hero.title1": "Générez des factures professionnelles en ",
    "hero.title2": "30 secondes",
    "hero.subtitle": "Calcul automatique de la TVA, export PDF, envoi par email — l'outil de facturation tout-en-un pour les freelances belges et français.",
    "hero.cta": "Générer ma première facture gratuitement",
    "hero.pricing": "Voir les tarifs",
    // Features
    "features.title": "Tout ce qu'il vous faut pour facturer",
    "features.subtitle": "Arrêtez de perdre du temps sur des tableurs. InvoiceAI gère tout.",
    "features.instant.title": "Génération instantanée",
    "features.instant.desc": "Créez des factures professionnelles en moins de 30 secondes grâce au remplissage automatique intelligent.",
    "features.vat.title": "Conforme TVA BE/FR",
    "features.vat.desc": "Calcul automatique de la TVA belge (21 %, 12 %, 6 %, 0 %) et TVA française.",
    "features.email.title": "Envoi par email",
    "features.email.desc": "Envoyez les factures directement aux clients par email avec suivi et confirmation de livraison.",
    // Pricing
    "pricing.title": "Tarifs simples et transparents",
    "pricing.subtitle": "Commencez gratuitement, évoluez quand vous grandissez.",
    "pricing.popular": "Le plus populaire",
    "pricing.starter": "Starter",
    "pricing.starter.desc": "Parfait pour commencer",
    "pricing.starter.cta": "Commencer gratuitement",
    "pricing.pro": "Pro",
    "pricing.pro.desc": "Pour les freelances actifs",
    "pricing.pro.cta": "Passer Pro",
    "pricing.business": "Business",
    "pricing.business.desc": "Pour les entreprises en croissance",
    "pricing.business.cta": "Choisir Business",
    "pricing.forever": "pour toujours",
    "pricing.perMonth": "/mois",
    "pricing.f.3inv": "3 factures/mois",
    "pricing.f.pdf": "Export PDF",
    "pricing.f.1client": "1 profil client",
    "pricing.f.templates": "Modèles de base",
    "pricing.f.unlimited": "Factures illimitées",
    "pricing.f.pdfEmail": "Export PDF & email",
    "pricing.f.unlimitedClients": "Clients illimités",
    "pricing.f.branding": "Personnalisation",
    "pricing.f.reminders": "Rappels de factures",
    "pricing.f.everything": "Tout dans Pro",
    "pricing.f.multiClient": "Gestion multi-clients",
    "pricing.f.autoReminders": "Rappels automatisés",
    "pricing.f.analytics": "Analyse du chiffre d'affaires",
    "pricing.f.support": "Support prioritaire",
    // Testimonials
    "testimonials.title": "Adoré par les freelances",
    "testimonials.1.quote": "InvoiceAI me fait gagner des heures chaque mois. Le calcul automatique de la TVA seul en vaut la peine !",
    "testimonials.2.quote": "Enfin un outil de facturation qui comprend la réglementation française. L'aperçu en direct est génial.",
    "testimonials.3.quote": "J'ai quitté Excel pour InvoiceAI et je n'ai jamais regardé en arrière. Mes clients adorent le rendu pro.",
    // CTA
    "cta.title": "Prêt à simplifier votre facturation ?",
    "cta.subtitle": "Rejoignez des milliers de freelances belges et français qui gagnent des heures chaque mois.",
    "cta.button": "Générer ma première facture gratuitement",
    // Footer
    "footer.text": "© 2026 InvoiceAI. Fait avec ❤️ pour les freelances de Belgique & France.",
    // Login
    "login.title": "Bon retour",
    "login.subtitle": "Connectez-vous à votre compte InvoiceAI",
    "login.email": "Email",
    "login.password": "Mot de passe",
    "login.forgot": "Mot de passe oublié ?",
    "login.submit": "Se connecter",
    "login.noAccount": "Pas encore de compte ?",
    "login.signup": "S'inscrire",
    // Signup
    "signup.title": "Créer votre compte",
    "signup.subtitle": "Commencez à générer des factures gratuitement",
    "signup.name": "Nom complet",
    "signup.submit": "Créer un compte",
    "signup.hasAccount": "Vous avez déjà un compte ?",
    "signup.signin": "Se connecter",
    // Forgot Password
    "forgot.title": "Réinitialiser votre mot de passe",
    "forgot.subtitle": "Nous vous enverrons un lien de réinitialisation",
    "forgot.submit": "Envoyer le lien",
    "forgot.back": "Retour à la connexion",
    // Dashboard
    "dashboard.title": "Tableau de bord",
    "dashboard.subtitle": "Gérez vos factures",
    "dashboard.newInvoice": "Nouvelle facture",
    "dashboard.totalInvoiced": "Total facturé",
    "dashboard.paid": "Payé",
    "dashboard.pending": "En attente",
    "dashboard.overdue": "En retard",
    "dashboard.search": "Rechercher des factures...",
    "dashboard.filterAll": "Tous les statuts",
    "dashboard.filterDraft": "Brouillon",
    "dashboard.filterSent": "Envoyé",
    "dashboard.filterPaid": "Payé",
    "dashboard.filterOverdue": "En retard",
    "dashboard.colInvoice": "N° Facture",
    "dashboard.colClient": "Client",
    "dashboard.colAmount": "Montant",
    "dashboard.colDate": "Date",
    "dashboard.colStatus": "Statut",
    "dashboard.statusDraft": "Brouillon",
    "dashboard.statusSent": "Envoyé",
    "dashboard.statusPaid": "Payé",
    "dashboard.statusOverdue": "En retard",
    // Settings
    "settings.title": "Paramètres",
    "settings.subtitle": "Gérez votre compte et vos paramètres de facturation",
    "settings.companyProfile": "Profil d'entreprise",
    "settings.companyName": "Nom de l'entreprise",
    "settings.vatNumber": "Numéro de TVA",
    "settings.address": "Adresse",
    "settings.iban": "IBAN",
    "settings.logo": "Logo",
    "settings.invoiceDefaults": "Paramètres de facture par défaut",
    "settings.defaultVat": "Taux de TVA par défaut",
    "settings.paymentTerms": "Conditions de paiement",
    "settings.invoicePrefix": "Préfixe de facture",
    "settings.emailSettings": "Paramètres email",
    "settings.replyTo": "Email de réponse",
    "settings.planBilling": "Abonnement & facturation",
    "settings.starterPlan": "Forfait Starter",
    "settings.starterDesc": "3 factures/mois · Gratuit pour toujours",
    "settings.upgrade": "Mettre à niveau",
    "settings.save": "Enregistrer",
    "settings.days": "jours",
    // Invoice Form
    "form.yourInfo": "Vos informations",
    "form.companyName": "Nom de l'entreprise",
    "form.vatNumber": "Numéro de TVA",
    "form.address": "Adresse",
    "form.email": "Email",
    "form.logo": "Logo",
    "form.clientInfo": "Informations client",
    "form.clientName": "Nom du client",
    "form.invoiceDetails": "Détails de la facture",
    "form.invoiceNumber": "Numéro de facture",
    "form.date": "Date",
    "form.paymentTerms": "Conditions de paiement",
    "form.lineItems": "Lignes de facturation",
    "form.description": "Description",
    "form.qty": "Qté",
    "form.unitPrice": "Prix unitaire",
    "form.vat": "TVA %",
    "form.addService": "Ajouter un service",
    "form.paymentNotes": "Paiement & notes",
    "form.iban": "IBAN",
    "form.notes": "Notes (optionnel)",
    "form.days": "jours",
    // Invoice Preview
    "preview.download": "Télécharger PDF",
    "preview.sendEmail": "Envoyer par email",
    "preview.sendTitle": "Envoyer la facture par email",
    "preview.recipient": "Email du destinataire",
    "preview.subject": "Objet",
    "preview.send": "Envoyer la facture",
    "preview.invoiceTitle": "FACTURE",
    "preview.billTo": "Facturer à",
    "preview.description": "Description",
    "preview.qty": "Qté",
    "preview.price": "Prix",
    "preview.vat": "TVA",
    "preview.total": "Total",
    "preview.subtotal": "Sous-total",
    "preview.vatLabel": "TVA",
    "preview.totalLabel": "Total",
    "preview.paymentDetails": "Détails de paiement",
    "preview.bankTransfer": "Virement bancaire",
    "preview.notes": "Notes",
  },
  en: {
    "nav.login": "Log in",
    "nav.getStarted": "Get Started",
    "nav.dashboard": "Dashboard",
    "nav.demoDashboard": "Demo Dashboard",
    "nav.logout": "Log out",
    "hero.badge": "🇧🇪 🇫🇷 Made for Belgian & French freelancers",
    "hero.title1": "Generate professional invoices in ",
    "hero.title2": "30 seconds",
    "hero.subtitle": "Auto-calculated VAT, PDF export, email sending — the all-in-one invoicing tool made for Belgian & French freelancers.",
    "hero.cta": "Generate My First Invoice Free",
    "hero.pricing": "View Pricing",
    "features.title": "Everything you need to invoice",
    "features.subtitle": "Stop wasting time on spreadsheets. InvoiceAI handles it all.",
    "features.instant.title": "Instant Generation",
    "features.instant.desc": "Create professional invoices in under 30 seconds with smart auto-fill and templates.",
    "features.vat.title": "VAT Compliant BE/FR",
    "features.vat.desc": "Automatic VAT calculation for Belgian (21%, 12%, 6%, 0%) and French rates.",

    "features.email.title": "Send by Email",
    "features.email.desc": "Send invoices directly to clients via email with tracking and delivery confirmation.",
    "pricing.title": "Simple, transparent pricing",
    "pricing.subtitle": "Start free, upgrade when you grow.",
    "pricing.popular": "Most Popular",
    "pricing.starter": "Starter",
    "pricing.starter.desc": "Perfect to get started",
    "pricing.starter.cta": "Start Free",
    "pricing.pro": "Pro",
    "pricing.pro.desc": "For active freelancers",
    "pricing.pro.cta": "Go Pro",
    "pricing.business": "Business",
    "pricing.business.desc": "For growing businesses",
    "pricing.business.cta": "Get Business",
    "pricing.forever": "forever",
    "pricing.perMonth": "/month",
    "pricing.f.3inv": "3 invoices/month",
    "pricing.f.pdf": "PDF export",
    "pricing.f.1client": "1 client profile",
    "pricing.f.templates": "Basic templates",
    "pricing.f.unlimited": "Unlimited invoices",
    "pricing.f.pdfEmail": "PDF export & email",
    "pricing.f.unlimitedClients": "Unlimited clients",
    "pricing.f.branding": "Custom branding",
    "pricing.f.reminders": "Invoice reminders",
    "pricing.f.everything": "Everything in Pro",
    "pricing.f.multiClient": "Multi-client management",
    "pricing.f.autoReminders": "Automated reminders",
    "pricing.f.analytics": "Revenue analytics",
    "pricing.f.support": "Priority support",
    "testimonials.title": "Loved by freelancers",
    "testimonials.1.quote": "InvoiceAI saved me hours every month. The VAT auto-calc alone is worth it — no more spreadsheet nightmares!",
    "testimonials.2.quote": "Finally an invoice tool that understands French freelancer regulations. The live preview is brilliant.",
    "testimonials.3.quote": "I switched from Excel to InvoiceAI and never looked back. My clients love the professional look.",
    "cta.title": "Ready to streamline your invoicing?",
    "cta.subtitle": "Join thousands of Belgian and French freelancers who save hours every month.",
    "cta.button": "Generate My First Invoice Free",
    "footer.text": "© 2026 InvoiceAI. Made with ❤️ for freelancers in Belgium & France.",
    "login.title": "Welcome back",
    "login.subtitle": "Sign in to your InvoiceAI account",
    "login.email": "Email",
    "login.password": "Password",
    "login.forgot": "Forgot password?",
    "login.submit": "Sign In",
    "login.noAccount": "Don't have an account?",
    "login.signup": "Sign up",
    "signup.title": "Create your account",
    "signup.subtitle": "Start generating invoices for free",
    "signup.name": "Full Name",
    "signup.submit": "Create Account",
    "signup.hasAccount": "Already have an account?",
    "signup.signin": "Sign in",
    "forgot.title": "Reset your password",
    "forgot.subtitle": "We'll send you a reset link",
    "forgot.submit": "Send Reset Link",
    "forgot.back": "Back to sign in",
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Manage your invoices",
    "dashboard.newInvoice": "New Invoice",
    "dashboard.totalInvoiced": "Total Invoiced",
    "dashboard.paid": "Paid",
    "dashboard.pending": "Pending",
    "dashboard.overdue": "Overdue",
    "dashboard.search": "Search invoices...",
    "dashboard.filterAll": "All Status",
    "dashboard.filterDraft": "Draft",
    "dashboard.filterSent": "Sent",
    "dashboard.filterPaid": "Paid",
    "dashboard.filterOverdue": "Overdue",
    "dashboard.colInvoice": "Invoice #",
    "dashboard.colClient": "Client",
    "dashboard.colAmount": "Amount",
    "dashboard.colDate": "Date",
    "dashboard.colStatus": "Status",
    "dashboard.statusDraft": "Draft",
    "dashboard.statusSent": "Sent",
    "dashboard.statusPaid": "Paid",
    "dashboard.statusOverdue": "Overdue",
    "settings.title": "Settings",
    "settings.subtitle": "Manage your account and invoice defaults",
    "settings.companyProfile": "Company Profile",
    "settings.companyName": "Company Name",
    "settings.vatNumber": "VAT Number",
    "settings.address": "Address",
    "settings.iban": "IBAN",
    "settings.logo": "Logo",
    "settings.invoiceDefaults": "Invoice Defaults",
    "settings.defaultVat": "Default VAT Rate",
    "settings.paymentTerms": "Payment Terms",
    "settings.invoicePrefix": "Invoice Prefix",
    "settings.emailSettings": "Email Settings",
    "settings.replyTo": "Reply-to Email",
    "settings.planBilling": "Plan & Billing",
    "settings.starterPlan": "Starter Plan",
    "settings.starterDesc": "3 invoices/month · Free forever",
    "settings.upgrade": "Upgrade",
    "settings.save": "Save Settings",
    "settings.days": "days",
    "form.yourInfo": "Your Information",
    "form.companyName": "Company Name",
    "form.vatNumber": "VAT Number",
    "form.address": "Address",
    "form.email": "Email",
    "form.logo": "Logo",
    "form.clientInfo": "Client Information",
    "form.clientName": "Client Name",
    "form.invoiceDetails": "Invoice Details",
    "form.invoiceNumber": "Invoice Number",
    "form.date": "Date",
    "form.paymentTerms": "Payment Terms",
    "form.lineItems": "Line Items",
    "form.description": "Description",
    "form.qty": "Qty",
    "form.unitPrice": "Unit Price",
    "form.vat": "VAT %",
    "form.addService": "Add Service",
    "form.paymentNotes": "Payment & Notes",
    "form.iban": "IBAN",
    "form.notes": "Notes (optional)",
    "form.days": "days",
    "preview.download": "Download PDF",
    "preview.sendEmail": "Send by Email",
    "preview.sendTitle": "Send Invoice by Email",
    "preview.recipient": "Recipient Email",
    "preview.subject": "Subject",
    "preview.send": "Send Invoice",
    "preview.invoiceTitle": "INVOICE",
    "preview.billTo": "Bill To",
    "preview.description": "Description",
    "preview.qty": "Qty",
    "preview.price": "Price",
    "preview.vat": "VAT",
    "preview.total": "Total",
    "preview.subtotal": "Subtotal",
    "preview.vatLabel": "VAT",
    "preview.totalLabel": "Total",
    "preview.paymentDetails": "Payment Details",
    "preview.bankTransfer": "Bank Transfer",
    "preview.notes": "Notes",
  },
  nl: {
    "nav.login": "Inloggen",
    "nav.getStarted": "Aan de slag",
    "nav.dashboard": "Dashboard",
    "nav.demoDashboard": "Demo Dashboard",
    "nav.logout": "Uitloggen",
    "hero.badge": "🇧🇪 🇫🇷 Gemaakt voor Belgische & Franse freelancers",
    "hero.title1": "Genereer professionele facturen in ",
    "hero.title2": "30 seconden",
    "hero.subtitle": "Automatische btw-berekening, PDF-export, e-mailverzending — de alles-in-één facturatietool voor Belgische & Franse freelancers.",
    "hero.cta": "Maak mijn eerste factuur gratis",
    "hero.pricing": "Bekijk prijzen",
    "features.title": "Alles wat je nodig hebt om te factureren",
    "features.subtitle": "Stop met tijdverspilling aan spreadsheets. InvoiceAI regelt alles.",
    "features.instant.title": "Directe generatie",
    "features.instant.desc": "Maak professionele facturen in minder dan 30 seconden met slim automatisch invullen.",
    "features.vat.title": "Btw-conform BE/FR",
    "features.vat.desc": "Automatische btw-berekening voor Belgische (21%, 12%, 6%, 0%) en Franse tarieven.",
    "features.email.title": "Verzenden per e-mail",
    "features.email.desc": "Verstuur facturen rechtstreeks naar klanten per e-mail met tracking en leveringsbevestiging.",
    "pricing.title": "Eenvoudige, transparante prijzen",
    "pricing.subtitle": "Begin gratis, upgrade wanneer je groeit.",
    "pricing.popular": "Meest populair",
    "pricing.starter": "Starter",
    "pricing.starter.desc": "Perfect om te starten",
    "pricing.starter.cta": "Gratis starten",
    "pricing.pro": "Pro",
    "pricing.pro.desc": "Voor actieve freelancers",
    "pricing.pro.cta": "Ga Pro",
    "pricing.business": "Business",
    "pricing.business.desc": "Voor groeiende bedrijven",
    "pricing.business.cta": "Kies Business",
    "pricing.forever": "voor altijd",
    "pricing.perMonth": "/maand",
    "pricing.f.3inv": "3 facturen/maand",
    "pricing.f.pdf": "PDF-export",
    "pricing.f.1client": "1 klantprofiel",
    "pricing.f.templates": "Basissjablonen",
    "pricing.f.unlimited": "Onbeperkte facturen",
    "pricing.f.pdfEmail": "PDF-export & e-mail",
    "pricing.f.unlimitedClients": "Onbeperkte klanten",
    "pricing.f.branding": "Eigen branding",
    "pricing.f.reminders": "Factuurherinneringen",
    "pricing.f.everything": "Alles in Pro",
    "pricing.f.multiClient": "Multi-klantenbeheer",
    "pricing.f.autoReminders": "Automatische herinneringen",
    "pricing.f.analytics": "Omzetanalyse",
    "pricing.f.support": "Prioritaire ondersteuning",
    "testimonials.title": "Geliefd bij freelancers",
    "testimonials.1.quote": "InvoiceAI bespaart me elke maand uren. De automatische btw-berekening alleen al is het waard!",
    "testimonials.2.quote": "Eindelijk een facturatietool die de Franse regelgeving begrijpt. Het live voorbeeld is briljant.",
    "testimonials.3.quote": "Ik ben overgestapt van Excel naar InvoiceAI en heb nooit meer teruggekeken. Mijn klanten vinden het prachtig.",
    "cta.title": "Klaar om je facturatie te stroomlijnen?",
    "cta.subtitle": "Sluit je aan bij duizenden Belgische en Franse freelancers die elke maand uren besparen.",
    "cta.button": "Maak mijn eerste factuur gratis",
    "footer.text": "© 2026 InvoiceAI. Gemaakt met ❤️ voor freelancers in België & Frankrijk.",
    "login.title": "Welkom terug",
    "login.subtitle": "Log in op je InvoiceAI-account",
    "login.email": "E-mail",
    "login.password": "Wachtwoord",
    "login.forgot": "Wachtwoord vergeten?",
    "login.submit": "Inloggen",
    "login.noAccount": "Nog geen account?",
    "login.signup": "Registreren",
    "signup.title": "Maak je account aan",
    "signup.subtitle": "Begin gratis met factureren",
    "signup.name": "Volledige naam",
    "signup.submit": "Account aanmaken",
    "signup.hasAccount": "Heb je al een account?",
    "signup.signin": "Inloggen",
    "forgot.title": "Wachtwoord herstellen",
    "forgot.subtitle": "We sturen je een herstelkoppeling",
    "forgot.submit": "Herstelkoppeling verzenden",
    "forgot.back": "Terug naar inloggen",
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Beheer je facturen",
    "dashboard.newInvoice": "Nieuwe factuur",
    "dashboard.totalInvoiced": "Totaal gefactureerd",
    "dashboard.paid": "Betaald",
    "dashboard.pending": "In afwachting",
    "dashboard.overdue": "Achterstallig",
    "dashboard.search": "Facturen zoeken...",
    "dashboard.filterAll": "Alle statussen",
    "dashboard.filterDraft": "Concept",
    "dashboard.filterSent": "Verzonden",
    "dashboard.filterPaid": "Betaald",
    "dashboard.filterOverdue": "Achterstallig",
    "dashboard.colInvoice": "Factuur #",
    "dashboard.colClient": "Klant",
    "dashboard.colAmount": "Bedrag",
    "dashboard.colDate": "Datum",
    "dashboard.colStatus": "Status",
    "dashboard.statusDraft": "Concept",
    "dashboard.statusSent": "Verzonden",
    "dashboard.statusPaid": "Betaald",
    "dashboard.statusOverdue": "Achterstallig",
    "settings.title": "Instellingen",
    "settings.subtitle": "Beheer je account en factuurinstellingen",
    "settings.companyProfile": "Bedrijfsprofiel",
    "settings.companyName": "Bedrijfsnaam",
    "settings.vatNumber": "Btw-nummer",
    "settings.address": "Adres",
    "settings.iban": "IBAN",
    "settings.logo": "Logo",
    "settings.invoiceDefaults": "Factuurstandaarden",
    "settings.defaultVat": "Standaard btw-tarief",
    "settings.paymentTerms": "Betalingsvoorwaarden",
    "settings.invoicePrefix": "Factuurprefix",
    "settings.emailSettings": "E-mailinstellingen",
    "settings.replyTo": "Antwoord-e-mail",
    "settings.planBilling": "Abonnement & facturering",
    "settings.starterPlan": "Starterspakket",
    "settings.starterDesc": "3 facturen/maand · Gratis voor altijd",
    "settings.upgrade": "Upgraden",
    "settings.save": "Instellingen opslaan",
    "settings.days": "dagen",
    "form.yourInfo": "Uw informatie",
    "form.companyName": "Bedrijfsnaam",
    "form.vatNumber": "Btw-nummer",
    "form.address": "Adres",
    "form.email": "E-mail",
    "form.logo": "Logo",
    "form.clientInfo": "Klantinformatie",
    "form.clientName": "Klantnaam",
    "form.invoiceDetails": "Factuurgegevens",
    "form.invoiceNumber": "Factuurnummer",
    "form.date": "Datum",
    "form.paymentTerms": "Betalingsvoorwaarden",
    "form.lineItems": "Factuurregels",
    "form.description": "Omschrijving",
    "form.qty": "Aantal",
    "form.unitPrice": "Eenheidsprijs",
    "form.vat": "Btw %",
    "form.addService": "Dienst toevoegen",
    "form.paymentNotes": "Betaling & opmerkingen",
    "form.iban": "IBAN",
    "form.notes": "Opmerkingen (optioneel)",
    "form.days": "dagen",
    "preview.download": "PDF downloaden",
    "preview.sendEmail": "Per e-mail verzenden",
    "preview.sendTitle": "Factuur per e-mail verzenden",
    "preview.recipient": "E-mail ontvanger",
    "preview.subject": "Onderwerp",
    "preview.send": "Factuur verzenden",
    "preview.invoiceTitle": "FACTUUR",
    "preview.billTo": "Factureren aan",
    "preview.description": "Omschrijving",
    "preview.qty": "Aantal",
    "preview.price": "Prijs",
    "preview.vat": "Btw",
    "preview.total": "Totaal",
    "preview.subtotal": "Subtotaal",
    "preview.vatLabel": "Btw",
    "preview.totalLabel": "Totaal",
    "preview.paymentDetails": "Betalingsgegevens",
    "preview.bankTransfer": "Bankoverschrijving",
    "preview.notes": "Opmerkingen",
  },
  de: {
    "nav.login": "Anmelden",
    "nav.getStarted": "Loslegen",
    "nav.dashboard": "Dashboard",
    "nav.demoDashboard": "Demo Dashboard",
    "nav.logout": "Abmelden",
    "hero.badge": "🇧🇪 🇫🇷 Für belgische & französische Freelancer",
    "hero.title1": "Erstellen Sie professionelle Rechnungen in ",
    "hero.title2": "30 Sekunden",
    "hero.subtitle": "Automatische MwSt.-Berechnung, PDF-Export, E-Mail-Versand — das All-in-One-Rechnungstool für belgische & französische Freelancer.",
    "hero.cta": "Meine erste Rechnung kostenlos erstellen",
    "hero.pricing": "Preise ansehen",
    "features.title": "Alles was Sie zum Rechnungsstellen brauchen",
    "features.subtitle": "Verschwenden Sie keine Zeit mehr mit Tabellenkalkulationen. InvoiceAI erledigt alles.",
    "features.instant.title": "Sofortige Erstellung",
    "features.instant.desc": "Erstellen Sie professionelle Rechnungen in unter 30 Sekunden mit intelligentem Auto-Fill.",
    "features.vat.title": "MwSt.-konform BE/FR",
    "features.vat.desc": "Automatische MwSt.-Berechnung für belgische (21%, 12%, 6%, 0%) und französische Sätze.",
    "features.email.title": "Per E-Mail senden",
    "features.email.desc": "Senden Sie Rechnungen direkt per E-Mail an Kunden mit Nachverfolgung und Zustellbestätigung.",
    "pricing.title": "Einfache, transparente Preise",
    "pricing.subtitle": "Starten Sie kostenlos, upgraden Sie bei Wachstum.",
    "pricing.popular": "Am beliebtesten",
    "pricing.starter": "Starter",
    "pricing.starter.desc": "Perfekt zum Einstieg",
    "pricing.starter.cta": "Kostenlos starten",
    "pricing.pro": "Pro",
    "pricing.pro.desc": "Für aktive Freelancer",
    "pricing.pro.cta": "Pro wählen",
    "pricing.business": "Business",
    "pricing.business.desc": "Für wachsende Unternehmen",
    "pricing.business.cta": "Business wählen",
    "pricing.forever": "für immer",
    "pricing.perMonth": "/Monat",
    "pricing.f.3inv": "3 Rechnungen/Monat",
    "pricing.f.pdf": "PDF-Export",
    "pricing.f.1client": "1 Kundenprofil",
    "pricing.f.templates": "Basis-Vorlagen",
    "pricing.f.unlimited": "Unbegrenzte Rechnungen",
    "pricing.f.pdfEmail": "PDF-Export & E-Mail",
    "pricing.f.unlimitedClients": "Unbegrenzte Kunden",
    "pricing.f.branding": "Eigenes Branding",
    "pricing.f.reminders": "Rechnungserinnerungen",
    "pricing.f.everything": "Alles in Pro",
    "pricing.f.multiClient": "Multi-Kunden-Verwaltung",
    "pricing.f.autoReminders": "Automatische Erinnerungen",
    "pricing.f.analytics": "Umsatzanalyse",
    "pricing.f.support": "Prioritärer Support",
    "testimonials.title": "Von Freelancern geliebt",
    "testimonials.1.quote": "InvoiceAI spart mir jeden Monat Stunden. Allein die automatische MwSt.-Berechnung ist es wert!",
    "testimonials.2.quote": "Endlich ein Rechnungstool, das die französischen Vorschriften versteht. Die Live-Vorschau ist genial.",
    "testimonials.3.quote": "Ich bin von Excel zu InvoiceAI gewechselt und habe nie zurückgeblickt. Meine Kunden lieben den professionellen Look.",
    "cta.title": "Bereit, Ihre Rechnungsstellung zu optimieren?",
    "cta.subtitle": "Schließen Sie sich Tausenden belgischen und französischen Freelancern an, die jeden Monat Stunden sparen.",
    "cta.button": "Meine erste Rechnung kostenlos erstellen",
    "footer.text": "© 2026 InvoiceAI. Mit ❤️ gemacht für Freelancer in Belgien & Frankreich.",
    "login.title": "Willkommen zurück",
    "login.subtitle": "Melden Sie sich bei Ihrem InvoiceAI-Konto an",
    "login.email": "E-Mail",
    "login.password": "Passwort",
    "login.forgot": "Passwort vergessen?",
    "login.submit": "Anmelden",
    "login.noAccount": "Noch kein Konto?",
    "login.signup": "Registrieren",
    "signup.title": "Konto erstellen",
    "signup.subtitle": "Beginnen Sie kostenlos mit der Rechnungserstellung",
    "signup.name": "Vollständiger Name",
    "signup.submit": "Konto erstellen",
    "signup.hasAccount": "Haben Sie bereits ein Konto?",
    "signup.signin": "Anmelden",
    "forgot.title": "Passwort zurücksetzen",
    "forgot.subtitle": "Wir senden Ihnen einen Zurücksetzungslink",
    "forgot.submit": "Link senden",
    "forgot.back": "Zurück zur Anmeldung",
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Verwalten Sie Ihre Rechnungen",
    "dashboard.newInvoice": "Neue Rechnung",
    "dashboard.totalInvoiced": "Gesamt fakturiert",
    "dashboard.paid": "Bezahlt",
    "dashboard.pending": "Ausstehend",
    "dashboard.overdue": "Überfällig",
    "dashboard.search": "Rechnungen suchen...",
    "dashboard.filterAll": "Alle Status",
    "dashboard.filterDraft": "Entwurf",
    "dashboard.filterSent": "Gesendet",
    "dashboard.filterPaid": "Bezahlt",
    "dashboard.filterOverdue": "Überfällig",
    "dashboard.colInvoice": "Rechnung #",
    "dashboard.colClient": "Kunde",
    "dashboard.colAmount": "Betrag",
    "dashboard.colDate": "Datum",
    "dashboard.colStatus": "Status",
    "dashboard.statusDraft": "Entwurf",
    "dashboard.statusSent": "Gesendet",
    "dashboard.statusPaid": "Bezahlt",
    "dashboard.statusOverdue": "Überfällig",
    "settings.title": "Einstellungen",
    "settings.subtitle": "Verwalten Sie Ihr Konto und Rechnungseinstellungen",
    "settings.companyProfile": "Firmenprofil",
    "settings.companyName": "Firmenname",
    "settings.vatNumber": "USt-IdNr.",
    "settings.address": "Adresse",
    "settings.iban": "IBAN",
    "settings.logo": "Logo",
    "settings.invoiceDefaults": "Rechnungsstandards",
    "settings.defaultVat": "Standard-MwSt.-Satz",
    "settings.paymentTerms": "Zahlungsbedingungen",
    "settings.invoicePrefix": "Rechnungspräfix",
    "settings.emailSettings": "E-Mail-Einstellungen",
    "settings.replyTo": "Antwort-E-Mail",
    "settings.planBilling": "Plan & Abrechnung",
    "settings.starterPlan": "Starter-Plan",
    "settings.starterDesc": "3 Rechnungen/Monat · Für immer kostenlos",
    "settings.upgrade": "Upgraden",
    "settings.save": "Einstellungen speichern",
    "settings.days": "Tage",
    "form.yourInfo": "Ihre Informationen",
    "form.companyName": "Firmenname",
    "form.vatNumber": "USt-IdNr.",
    "form.address": "Adresse",
    "form.email": "E-Mail",
    "form.logo": "Logo",
    "form.clientInfo": "Kundeninformationen",
    "form.clientName": "Kundenname",
    "form.invoiceDetails": "Rechnungsdetails",
    "form.invoiceNumber": "Rechnungsnummer",
    "form.date": "Datum",
    "form.paymentTerms": "Zahlungsbedingungen",
    "form.lineItems": "Rechnungspositionen",
    "form.description": "Beschreibung",
    "form.qty": "Menge",
    "form.unitPrice": "Einzelpreis",
    "form.vat": "MwSt. %",
    "form.addService": "Dienst hinzufügen",
    "form.paymentNotes": "Zahlung & Anmerkungen",
    "form.iban": "IBAN",
    "form.notes": "Anmerkungen (optional)",
    "form.days": "Tage",
    "preview.download": "PDF herunterladen",
    "preview.sendEmail": "Per E-Mail senden",
    "preview.sendTitle": "Rechnung per E-Mail senden",
    "preview.recipient": "Empfänger-E-Mail",
    "preview.subject": "Betreff",
    "preview.send": "Rechnung senden",
    "preview.invoiceTitle": "RECHNUNG",
    "preview.billTo": "Rechnungsempfänger",
    "preview.description": "Beschreibung",
    "preview.qty": "Menge",
    "preview.price": "Preis",
    "preview.vat": "MwSt.",
    "preview.total": "Gesamt",
    "preview.subtotal": "Zwischensumme",
    "preview.vatLabel": "MwSt.",
    "preview.totalLabel": "Gesamt",
    "preview.paymentDetails": "Zahlungsdetails",
    "preview.bankTransfer": "Banküberweisung",
    "preview.notes": "Anmerkungen",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(
    () => (localStorage.getItem("invoiceai-lang") as Language) || "fr"
  );

  const setLang = (l: Language) => {
    localStorage.setItem("invoiceai-lang", l);
    setLangState(l);
  };

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
